POST http://localhost:3000 HTTP/1.1
Content-Type: application/json
Content-Length: 27

{
    "name":"sample9",
    "hash":"krishnateja",
    "c":"1",
    "docker":"1",
    "lang":"java",
    "input":"'new sample' 'olld'",
    "code":"class Main {\n public static void main(String args[]) {\n // first input\n System.out.println(args[0]);\n // second input\n System.out.println(args[1]);\n }\n }"

}

